### ISSUE TITLE
Error al realizar una llamada Post con HttpFormmatter json

### ISSUE THREAD

**Issue by tacheleu** [bernatvadell/WebApiProxy#1]
Obtengo el siguiente mensaje de error: El tipo 'System.Net.Http.ObjectContent`1[System.Object]' no se puede serializar. 

Si cambio el método a Get, me dice que la URL es demasiado larga

**Comment by bernatvadell** [comment]
Buenas @tacheleu 

Acabo de actualizar el nuget con la última versión del repositorio.

Prueba a instalar la última versión:
Install-Package WebApi.Proxy.Client -version 1.0.3

En la prueba realizada la petición ha quedado asi:

POST http://maps.googleapis.com/maps/api/geocode/json HTTP/1.1
Content-Type: application/json; charset=utf-8
Host: maps.googleapis.com
Content-Length: 67
Expect: 100-continue
Pragma: no-cache

{"address":"1600 Amphitheatre Parkway, Mountain View, CA","key":""}

Saludos
